[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/favicon.ico"
    [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.png"
    [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/site.webmanifest"
    [headers.values]
    Content-Type = "application/manifest+json" 