[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/favicon.ico"
    [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.png"
    [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/site.webmanifest"
    [headers.values]
    Content-Type = "application/manifest+json" 